# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.DecimalField(decimal_places=3, max_digits=4)),
                ('holiday_name', models.CharField(max_length=256)),
                ('holiday_type', models.CharField(choices=[('Genral', 'Genral'), ('Restricted', 'Restricted')], default='Genral', max_length=20)),
                ('holiday_icon', models.ImageField(blank=True, upload_to='holiday_ico')),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
