# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_icon',
            field=models.ImageField(blank=True, upload_to='holiday_icon'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
