# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_auto_20180109_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['holiday_date']},
        ),
    ]
