# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20180111_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapply',
            name='status',
            field=models.CharField(default='Awaiting', max_length=256),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='status_by',
            field=models.CharField(default='', max_length=256),
        ),
    ]
