# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 06:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('phone', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(9)])),
                ('address', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('del_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
