# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverules',
            old_name='rules',
            new_name='leave_rules',
        ),
        migrations.AddField(
            model_name='leaverules',
            name='leave_type',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
