# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 12:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_auto_20180111_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default='')),
                ('no_of_days', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tag_to', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leaverules',
            name='leave_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave.LeaveRules'),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
