# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 07:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(15), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
