# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_auto_20180108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
